import { useId, type ReactNode } from 'react';
import { Button } from '../../design/primitives';
import type { UnknownRecord } from '../../protocol';
import { record, text } from './agentClassesModel';
import type { ActionDraft } from './actionModel';
import styles from './ControlCenter.module.css';
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className={styles.field}><span>{label}</span>{children}</label>; }
export function ActionFields({ draft, actions, roles, change }: { draft: ActionDraft; actions: UnknownRecord[]; roles: UnknownRecord[]; change: (draft: ActionDraft) => void }) {
  const roleId = useId(); const actionId = useId();
  const update = (key: string, entry: unknown) => { const values = { ...draft.values }; if (entry === undefined) delete values[key]; else values[key] = entry; change({ ...draft, values }); };
  const input = (key: string, label: string, numeric = false) => <Field key={key} label={label}><input type={numeric ? 'number' : 'text'} min={numeric ? 0 : undefined} step={numeric ? 1 : undefined} value={text(draft.values[key])} onChange={(event) => update(key, event.target.value)} /></Field>;
  const changeTransition = (index: number, row: UnknownRecord) => change({ ...draft, transitions: draft.transitions.map((item, n) => n === index ? row : item) });
  const agent = draft.values.agent; const inline = agent && typeof agent === 'object';
  return <div className={styles.catalogFields}>
    <div className={styles.formGrid}><Field label="Name"><input value={draft.name} onChange={(event) => change({ ...draft, name: event.target.value })} /></Field><Field label="Scope"><select value={draft.scope} onChange={(event) => change({ ...draft, scope: event.target.value })}><option value="project">Project</option><option value="user">User</option></select></Field>{input('description', 'Description')}{input('group', 'Target group')}<Field label="Labels"><input value={draft.labels} onChange={(event) => change({ ...draft, labels: event.target.value })} /></Field></div>
    <details open><summary>Agent and execution</summary><Field label="Agent configuration"><select value={inline ? 'inline' : 'role'} onChange={(event) => update('agent', event.target.value === 'inline' ? {} : '')}><option value="role">Role or template</option><option value="inline">Inline agent</option></select></Field>
      {inline ? <div className={styles.formGrid}>{([['name_prefix', 'Agent name prefix'], ['command', 'Boot command'], ['directory', 'Working directory'], ['tab_color', 'Tab color'], ['profile', 'Terminal profile'], ['shell', 'Shell']] as const).map(([key, label]) => <Field key={key} label={label}><input value={text(record(agent)[key])} onChange={(event) => update('agent', { ...record(agent), [key]: event.target.value })} /></Field>)}</div> : <Field label="Agent role or template"><input list={roleId} value={text(agent)} onChange={(event) => update('agent', event.target.value)} placeholder="Inherit worker defaults" /><datalist id={roleId}>{Array.from(new Set(roles.map((row) => text(row.name)))).map((name) => <option key={name} value={name} />)}</datalist></Field>}
      <div className={styles.formGrid}><Field label="Create worktree"><select value={draft.values.worktree === undefined ? '' : draft.values.worktree === true ? 'true' : 'false'} onChange={(event) => update('worktree', event.target.value === '' ? undefined : event.target.value === 'true')}><option value="">Inherit default</option><option value="true">Enabled</option><option value="false">Disabled</option></select></Field>{input('review_required_above_loc', 'Review above LOC', true)}{input('max_depth', 'Maximum pipeline depth', true)}</div>
      <div className={styles.checkRow}>{([['auto_close_on_done', 'Auto-close on done'], ['disable_role_preamble', 'Disable role preamble'], ['implementation_depth', 'Implementation-depth gate']] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={draft.values[key] === true} onChange={(event) => update(key, event.target.checked)} />{label}</label>)}</div>
    </details>
    <Field label="Prompt"><textarea value={text(draft.values.prompt)} onChange={(event) => update('prompt', event.target.value)} spellCheck={false} /></Field><p className={styles.note}>Only the prompt renders template variables. Include {'{{ TASK }}'} or {'{{ torque.task.title }}'}.</p>
    <details open><summary>Transitions</summary><datalist id={actionId}>{Array.from(new Set(actions.filter((row) => row.shadowed !== true).map((row) => text(row.name)))).map((name) => <option key={name} value={name} />)}</datalist>
      {draft.transitions.map((row, index) => <fieldset className={styles.catalogTerminal} key={index}><legend>Transition {index + 1}</legend><Field label={`Transition ${index + 1} type`}><select value={row.ask === true ? 'ask' : 'action'} onChange={(event) => { const next = { ...row }; if (event.target.value === 'ask') { next.ask = true; for (const key of ['action', 'target', 'status', 'loc_gate']) delete next[key]; } else { delete next.ask; next.action = ''; } changeTransition(index, next); }}><option value="action">Action</option><option value="ask">Ask a human</option></select></Field>
        {row.ask !== true ? <div className={styles.formGrid}><Field label={`Transition ${index + 1} action`}><input list={actionId} value={text(row.action)} onChange={(event) => changeTransition(index, { ...row, action: event.target.value })} /></Field><Field label={`Transition ${index + 1} target`}><select value={text(row.target)} onChange={(event) => changeTransition(index, { ...row, target: event.target.value })}><option value="">New agent</option><option value="self">Self</option><option value="parent">Parent</option><option value="root">Root</option>{!['', 'self', 'parent', 'root'].includes(text(row.target)) ? <option value={text(row.target)}>{text(row.target)}</option> : null}</select></Field><Field label={`Transition ${index + 1} status`}><input value={text(row.status)} onChange={(event) => changeTransition(index, { ...row, status: event.target.value })} /></Field></div> : null}
        <Field label={`Transition ${index + 1} when`}><textarea value={text(row.when)} onChange={(event) => changeTransition(index, { ...row, when: event.target.value })} /></Field>
        {row.ask !== true ? <><label><input type="checkbox" checked={Boolean(row.loc_gate)} onChange={(event) => { const next = { ...row }; if (event.target.checked) next.loc_gate = { ship_direct_max: 50, review_default_above: 150, self_review_bypass_allowed: false }; else delete next.loc_gate; changeTransition(index, next); }} />Transition {index + 1} LOC gate</label>{row.loc_gate ? <details open><summary>Transition {index + 1} LOC thresholds</summary><div className={styles.formGrid}>{([['ship_direct_max', 'Ship direct up to LOC'], ['review_default_above', 'Review above LOC']] as const).map(([key, label]) => <Field key={key} label={`Transition ${index + 1} ${label}`}><input type="number" min="0" step="1" value={text(record(row.loc_gate)[key])} onChange={(event) => changeTransition(index, { ...row, loc_gate: { ...record(row.loc_gate), [key]: event.target.value } })} /></Field>)}</div><label><input type="checkbox" checked={record(row.loc_gate).self_review_bypass_allowed === true} onChange={(event) => changeTransition(index, { ...row, loc_gate: { ...record(row.loc_gate), self_review_bypass_allowed: event.target.checked } })} />Transition {index + 1} allow self-review bypass</label></details> : null}</> : null}
        <Button onPress={() => change({ ...draft, transitions: draft.transitions.filter((_item, n) => n !== index) })}>Remove transition {index + 1}</Button></fieldset>)}
      <Button onPress={() => change({ ...draft, transitions: [...draft.transitions, { action: '', when: '' }] })}>Add transition</Button>
    </details>
    <details><summary>Companion terminals</summary>{draft.terminals.map((row, index) => <div className={styles.catalogTerminal} key={index}>{(['name', 'command'] as const).map((key) => <Field key={key} label={`Terminal ${index + 1} ${key}`}><input value={text(row[key])} onChange={(event) => change({ ...draft, terminals: draft.terminals.map((item, n) => n === index ? { ...item, [key]: event.target.value } : item) })} /></Field>)}<Button onPress={() => change({ ...draft, terminals: draft.terminals.filter((_item, n) => n !== index) })}>Remove terminal {index + 1}</Button></div>)}<Button onPress={() => change({ ...draft, terminals: [...draft.terminals, { name: '', command: '' }] })}>Add terminal</Button></details>
  </div>;
}
