import { useId, type ReactNode } from 'react';
import { useAppSelector } from '../../app/hooks';
import { selectProviders } from '../../app/store';
import { Button } from '../../design/primitives';
import { record, text } from './agentClassesModel';
import type { CatalogDraft, CatalogKind } from './catalogModel';
import styles from './ControlCenter.module.css';
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className={styles.field}><span>{label}</span>{children}</label>; }
export function CatalogFields({ kind, draft, change }: { kind: CatalogKind; draft: CatalogDraft; change: (draft: CatalogDraft) => void }) {
  const providers = useAppSelector(selectProviders); const providerList = useId();
  const value = (key: string) => text(draft.values[key]);
  const update = (key: string, entry: unknown) => { const values = { ...draft.values }; if (entry === undefined) delete values[key]; else values[key] = entry; change({ ...draft, values }); };
  const input = (key: string, label: string, numeric = false) => <Field key={key} label={label}><input type={numeric ? 'number' : 'text'} min={numeric ? 0 : undefined} step={numeric ? 1 : undefined} value={value(key)} onChange={(event) => update(key, event.target.value)} /></Field>;
  const area = (key: string, label: string) => <Field key={key} label={label}><textarea value={value(key)} onChange={(event) => update(key, event.target.value)} /></Field>;
  const flag = (key: string, label: string) => <Field key={key} label={label}><select value={draft.values[key] === undefined ? '' : draft.values[key] === true ? 'true' : 'false'} onChange={(event) => update(key, event.target.value === '' ? undefined : event.target.value === 'true')}><option value="">Inherit default</option><option value="true">Enabled</option><option value="false">Disabled</option></select></Field>;
  return <div className={styles.catalogFields}>
    <div className={styles.formGrid}><Field label="Name"><input value={draft.name} onChange={(event) => change({ ...draft, name: event.target.value })} /></Field><Field label="Scope"><select value={draft.scope} onChange={(event) => change({ ...draft, scope: event.target.value })}><option value="project">Project</option><option value="user">User</option></select></Field>{kind !== 'specialization' ? input('display_name', 'Display name') : null}{input('description', 'Description')}</div>
    {kind !== 'specialization' ? <details open><summary>Provider and launch</summary><div className={styles.formGrid}><Field label="Agent CLI"><input list={providerList} value={value('provider')} onChange={(event) => update('provider', event.target.value)} placeholder="Inherit provider" /><datalist id={providerList}>{providers.map((entry, index) => { const item = record(entry); return <option key={index} value={text(item.id, text(item.name))}>{text(item.display_name, text(item.name))}</option>; })}</datalist></Field>{input('command', 'Command override')}{input('model', 'Model')}{input('permissions', 'Permissions')}{input('max_turns', 'Max turns', true)}{input('reasoning_effort', 'Reasoning effort')}{input('fast_mode', 'Fast mode')}{input('runner_backend', 'Runner backend')}</div></details> : null}
    <details open><summary>Behavior</summary>{area('preamble', 'Preamble')}<Field label="Priorities (one per line)"><textarea value={draft.priorities} onChange={(event) => change({ ...draft, priorities: event.target.value })} /></Field>{kind !== 'specialization' ? <>{area('system_prompt', 'System prompt')}{area('initial_prompt', 'Initial prompt')}<div className={styles.formGrid}>{flag('session_resume', 'Resume session on relaunch')}{input('idle_timeout', 'Idle timeout (minutes)', true)}</div></> : null}</details>
    {kind !== 'specialization' ? <><details><summary>Appearance</summary><div className={styles.formGrid}>{input('tab_color', 'Tab color')}{input('icon', 'Icon')}</div></details><details><summary>Worktree</summary><div className={styles.formGrid}>{flag('worktree', 'Enable git worktree')}{input('worktree_base_branch', 'Base branch')}{flag('worktree_auto_checkpoint', 'Auto-checkpoint on stop')}{flag('checkpoint_on_progress', 'Checkpoint on progress')}{flag('worktree_merge_squash', 'Squash on merge')}</div></details><details><summary>Environment and terminals</summary><Field label="Environment (KEY=VALUE per line)"><textarea value={draft.environment} onChange={(event) => change({ ...draft, environment: event.target.value })} /></Field>{input('env_file', 'Environment file')}
      <h3>Child terminals</h3>{draft.terminals.map((terminal, index) => <div className={styles.catalogTerminal} key={index}><Field label={`Terminal ${index + 1} name`}><input value={text(terminal.name)} onChange={(event) => change({ ...draft, terminals: draft.terminals.map((item, n) => n === index ? { ...item, name: event.target.value } : item) })} /></Field><Field label={`Terminal ${index + 1} command`}><input value={text(terminal.command)} onChange={(event) => change({ ...draft, terminals: draft.terminals.map((item, n) => n === index ? { ...item, command: event.target.value } : item) })} /></Field><Button type="button" onPress={() => change({ ...draft, terminals: draft.terminals.filter((_item, n) => n !== index) })}>Remove terminal {index + 1}</Button></div>)}<Button type="button" onPress={() => change({ ...draft, terminals: [...draft.terminals, { name: '', command: '' }] })}>Add terminal</Button>
    </details></> : null}
  </div>;
}
