//! libghostty FFI.
//!
//! Raw bindings are generated by `bindgen` in `build.rs` and included below
//! when the `ffi` feature is enabled. Without the feature, this module
//! exposes a stub surface-registration API so the crate still compiles for
//! CI builds and non-macOS targets.

use std::collections::HashMap;
use std::sync::Mutex;

use once_cell::sync::Lazy;

#[cfg(feature = "ffi")]
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    improper_ctypes,
    clippy::all
)]
pub mod sys {
    //! Raw bindgen output for libghostty's C API.
    include!(concat!(env!("OUT_DIR"), "/ghostty_sys.rs"));
}

static SURFACES: Lazy<Mutex<HashMap<String, SurfaceStub>>> =
    Lazy::new(|| Mutex::new(HashMap::new()));

#[derive(Debug)]
struct SurfaceStub {
    #[allow(dead_code)]
    cell_id: String,
}

/// Register a rendering surface for a cell.
///
/// With `ffi`, the actual `ghostty_surface_new` call lives in the UI crate
/// that owns the NSView. This module only tracks which cells have surfaces
/// so we can enforce one-surface-per-cell.
pub fn register_cell_surface(cell_id: &str) -> anyhow::Result<()> {
    let mut map = SURFACES.lock().unwrap();
    if map.contains_key(cell_id) {
        anyhow::bail!("cell '{cell_id}' already has a surface");
    }
    map.insert(
        cell_id.to_string(),
        SurfaceStub {
            cell_id: cell_id.to_string(),
        },
    );
    Ok(())
}

pub fn release_cell_surface(cell_id: &str) {
    let mut map = SURFACES.lock().unwrap();
    map.remove(cell_id);
}

pub fn surface_count() -> usize {
    SURFACES.lock().unwrap().len()
}

#[cfg(all(feature = "ffi", test))]
mod ffi_smoke {
    use super::sys;

    #[test]
    fn symbols_linked() {
        // Just reference a couple of symbols so the linker can't drop the
        // library entirely. Not calling them — that needs a full app context.
        let _ = sys::ghostty_app_new as unsafe extern "C" fn(_, _) -> _;
        let _ = sys::ghostty_config_new as unsafe extern "C" fn() -> _;
        let _ = sys::ghostty_surface_new as unsafe extern "C" fn(_, _) -> _;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex as StdMutex;

    /// Serialize tests that share the process-wide `SURFACES` map —
    /// otherwise parallel runs of `register_then_release_roundtrip` and
    /// `duplicate_rejected` see each other's entries and the counts race.
    static SURFACES_LOCK: StdMutex<()> = StdMutex::new(());

    #[test]
    fn register_then_release_roundtrip() {
        let _g = SURFACES_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        assert_eq!(
            surface_count(),
            0,
            "test isolation broken — unexpected entries"
        );
        register_cell_surface("cell-x").unwrap();
        register_cell_surface("cell-y").unwrap();
        assert_eq!(surface_count(), 2);
        release_cell_surface("cell-x");
        assert_eq!(surface_count(), 1);
        release_cell_surface("cell-y");
        assert_eq!(surface_count(), 0);
    }

    #[test]
    fn duplicate_rejected() {
        let _g = SURFACES_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        register_cell_surface("cell-dup").unwrap();
        assert!(register_cell_surface("cell-dup").is_err());
        release_cell_surface("cell-dup");
    }
}
