import type { UnknownRecord } from '../../protocol';
import { aiCount, aiRecord, aiText, aiTime, aiTone } from './aiRuntimeModel';
import { AiIndexStart } from './AiIndexStart';
import styles from './AiRuntime.module.css';
function Status({ value, fallback = 'unknown' }: { value: unknown; fallback?: string }) { const status = aiText(value, fallback); return <strong data-state={status} data-tone={aiTone(status)}>{status.replaceAll('_', ' ')}</strong>; }
function Time({ value }: { value: unknown }) { const iso = aiTime(value); return iso ? <time dateTime={iso}>{new Date(iso).toLocaleString()}</time> : <>Never</>; }
function Counts({ value, fields }: { value: unknown; fields: [string, string][] }) { const counts = aiRecord(value); return <div className={styles.counts}>{fields.map(([key, label]) => <span key={key}>{label} {aiCount(counts[key])}</span>)}</div>; }
export function AiRuntime({ settings, disabled = false }: { settings: UnknownRecord; disabled?: boolean }) {
  const embeddings = aiRecord(settings.embeddings); const dependency = aiRecord(embeddings.dependency); const index = aiRecord(settings.index); const warning = aiRecord(index.rebuild_warning); const job = aiRecord(index.current_job);
  const boot = aiRecord(settings.boot_summary); const metering = aiRecord(settings.metering); const bootStatus = aiText(boot.status, 'unknown').toLowerCase();
  const packages = Array.isArray(dependency.packages) ? dependency.packages.filter((value): value is string => typeof value === 'string').join(', ') : '';
  return <>
    <section className={styles.panel} aria-label="Embedding dependencies"><h4>Embedding dependencies</h4><dl><dt>Runtime</dt><dd>{aiText(embeddings.runtime, 'sentence_transformers')}</dd><dt>Dependency</dt><dd><Status value={dependency.status} />{packages ? ` · ${packages}` : ''}</dd>{dependency.status === 'missing' ? <><dt>Install</dt><dd><code>{aiText(dependency.install_hint, 'make ai-deps')}</code></dd></> : null}</dl><p>First use downloads local embedding model weights. Models such as BAAI/bge-m3 can be GB-scale.</p></section>
    <section className={styles.panel} aria-label="Vector index"><h4>Vector index</h4><dl><dt>Status</dt><dd><Status value={index.status} fallback="disabled" /></dd><dt>Counts</dt><dd><Counts value={index.counts} fields={[["sources", "Sources"], ["chunks", "Chunks"], ["indexed", "Indexed"], ["pending", "Pending"], ["stale", "Stale"], ["errors", "Errors"]]} /></dd><dt>Active model</dt><dd>{aiText(embeddings.active_model_id, '—')}{aiCount(embeddings.active_dims) > 0 ? ` · ${aiCount(embeddings.active_dims)} dims` : ''}</dd><dt>Desired model</dt><dd>{aiText(embeddings.desired_model_id, aiText(embeddings.model_id, '—'))}</dd><dt>Last built</dt><dd><Time value={index.last_built_at} /></dd>{aiText(index.last_error) ? <><dt>Last error</dt><dd data-tone="danger">{aiText(index.last_error)}</dd></> : null}{warning.required ? <><dt>Rebuild</dt><dd data-tone="warning">{aiText(warning.reason, 'Embedding settings changed; a full rebuild is required.')}</dd></> : null}{Object.keys(job).length ? <><dt>Job</dt><dd><Status value={job.status} fallback="queued" />{aiText(job.mode) ? ` · ${aiText(job.mode)}` : ''}{aiText(job.id) ? <p>{aiText(job.id)}</p> : null}{aiText(job.message) ? <p>{aiText(job.message)}</p> : null}{aiText(job.error) ? <p data-tone="danger">{aiText(job.error)}</p> : null}</dd></> : null}</dl><AiIndexStart disabled={disabled} /></section>
    <section className={styles.panel} aria-label="Boot summaries and metering"><h4>Boot summaries and metering</h4><dl><dt>Summary</dt><dd><Status value={bootStatus} />{boot.enabled === false ? ' · disabled in settings' : ''}</dd><dt>Counts</dt><dd><Counts value={boot.counts} fields={[["ready", "Ready"], ["stale", "Stale"], ["errors", "Errors"]]} /></dd><dt>Refreshed</dt><dd><Time value={boot.last_refreshed_at} /></dd>{aiText(boot.last_error) && bootStatus !== 'ready' ? <><dt>Last error</dt><dd data-tone="danger">{aiText(boot.last_error)}</dd></> : null}<dt>Metering 24h</dt><dd><Counts value={metering} fields={[["calls_24h", "Calls"], ["input_tokens_24h", "Input"], ["output_tokens_24h", "Output"], ["cache_read_input_tokens_24h", "Cache read"]]} /></dd><dt>Last call</dt><dd><Time value={metering.last_call_at} /></dd></dl></section>
  </>;
}
