import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) {
  const response = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row };
  expect(response.ok, response.error).toBe(true); expect(response.data.type).not.toBe('error'); return response.data;
}
test('Actions preview unsaved drafts, retain reconnect edits and acknowledge typed authoring and lifecycle changes', async ({ page, request }) => {
  test.setTimeout(120_000);
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: { port: number; profile: string } } }).data.runtime;
  expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const project = mkdtempSync(join(tmpdir(), 'torque-actions-parity-')); const group = `Actions ${Date.now()}`; const name = 'parity/build';
  const definition: Row = { prompt: 'Saved {{ TASK }} {{ SCOPE | default("all") }}', description: 'Original description', worktree: false, max_depth: 7, deliverable: { required: true, kind: 'report' }, agent: { name_prefix: 'worker', env_vars: { KEEP: 'yes' }, shell: '/bin/zsh' }, transitions: [{ action: 'parity/review', when: 'Ready', target: 'parent', loc_gate: { ship_direct_max: 0, review_default_above: 100, self_review_bypass_allowed: false } }], terminals: [{ name: 'logs', command: 'echo logs' }] };
  try {
    await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'update_group_settings', group, settings: { default_directory: project, git_worktree: false } }); await command(request, { cmd: 'ui_select_group', group });
    await command(request, { cmd: 'save_action', name, scope: 'project', group, action: definition });
    let socket: WebSocketRoute | undefined; let connections = 0; let refusal = ''; let hold = false; let release: (() => void) | undefined; const calls: Row[] = [];
    await page.routeWebSocket(/\/ws\?/, (connection) => { connection.connectToServer(); socket = connection; connections += 1; });
    const reconnect = async () => { const before = connections; await socket!.close({ code: 1012, reason: 'Actions reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); };
    await page.route('**/api/cmd', async (route) => {
      const data = route.request().postDataJSON() as Row; calls.push(data);
      if (data.cmd === refusal) { await route.fulfill({ json: { ok: true, data: { type: 'error', message: 'Injected action refusal' } } }); return; }
      if (hold && data.cmd === 'save_action') { const response = await route.fetch(); await new Promise<void>((resolve) => { release = resolve; }); await route.fulfill({ response }); return; }
      await route.continue();
    });
    await page.goto('/'); await page.getByRole('button', { name: /◎ Control/ }).click(); await page.getByRole('button', { name: 'Actions', exact: true }).click(); const library = page.getByRole('region', { name: 'Actions library', exact: true });
    await library.getByRole('button', { name: /parity\/build\s*project/ }).click(); const prompt = library.getByRole('textbox', { name: 'Prompt', exact: true }); await expect(prompt).toHaveValue(definition.prompt as string);
    await prompt.fill('Unsaved {{ TASK }} {{ SCOPE | default("all") }}'); await prompt.evaluate((node: HTMLTextAreaElement) => { node.setSelectionRange(2, 7); node.dataset.actionAnchor = 'original'; }); const scroll = await prompt.evaluate((node) => node.closest('form')!.parentElement!.scrollTop);
    await command(request, { cmd: 'save_action', name, scope: 'project', group, action: { ...definition, description: 'Remote description', prompt: 'Remote {{ TASK }}' } });
    await reconnect(); await expect(library.getByRole('textbox', { name: 'Description', exact: true })).toHaveValue('Remote description'); await expect(prompt).toHaveValue('Unsaved {{ TASK }} {{ SCOPE | default("all") }}'); await expect(prompt).toBeFocused(); await expect(prompt).toHaveAttribute('data-action-anchor', 'original'); expect(await prompt.evaluate((node: HTMLTextAreaElement) => [node.selectionStart, node.selectionEnd])).toEqual([2, 7]); expect(await prompt.evaluate((node) => node.closest('form')!.parentElement!.scrollTop)).toBeCloseTo(scroll, 0);
    refusal = 'get_action'; await reconnect(); await expect(library.getByRole('alert')).toContainText('Definition refresh failed'); refusal = ''; await library.getByRole('button', { name: 'Retry definition' }).click(); await expect(library.getByRole('alert')).toHaveCount(0);
    await library.getByRole('textbox', { name: 'Preview TASK', exact: true }).fill('Example task'); await library.getByRole('textbox', { name: 'Preview SCOPE', exact: true }).fill('focused scope'); await library.getByRole('button', { name: 'Preview', exact: true }).click(); await expect(library.getByLabel('Rendered action prompt')).toHaveText('Unsaved Example task focused scope');
    expect((await command(request, { cmd: 'get_action', name, scope: 'project', group })).action).toMatchObject({ prompt: 'Remote {{ TASK }}' });
    await prompt.fill('Final {{ TASK }} {{ SCOPE | default("all") }}'); await expect(library.getByText(/Draft changed/)).toBeVisible();
    await library.getByRole('textbox', { name: 'Boot command', exact: true }).fill('generic-worker'); await library.getByRole('spinbutton', { name: 'Review above LOC', exact: true }).fill('0'); await library.getByRole('combobox', { name: 'Transition 1 target', exact: true }).selectOption('root'); await library.getByRole('textbox', { name: 'Transition 1 status', exact: true }).fill('Reviewing');
    await library.getByRole('button', { name: 'Add transition', exact: true }).click(); await library.getByRole('combobox', { name: 'Transition 2 type', exact: true }).selectOption('ask'); await library.getByRole('textbox', { name: 'Transition 2 when', exact: true }).fill('Operator approval');
    await library.getByText('Companion terminals', { exact: true }).click(); await library.getByRole('textbox', { name: 'Terminal 1 command', exact: true }).fill('echo changed');
    refusal = 'save_action'; await library.getByRole('button', { name: 'Save action', exact: true }).click(); await expect(library.getByRole('alert')).toContainText('Injected action refusal'); await expect(prompt).toHaveValue('Final {{ TASK }} {{ SCOPE | default("all") }}'); refusal = ''; await library.getByRole('button', { name: 'Save action', exact: true }).click(); await expect(library.getByText(`Saved project ${name}`, { exact: true })).toBeVisible();
    const saved = (await command(request, { cmd: 'get_action', name, scope: 'project', group })).action as Row; expect(saved).toMatchObject({ ...definition, prompt: 'Final {{ TASK }} {{ SCOPE | default("all") }}', description: 'Remote description', review_required_above_loc: 0, agent: { ...definition.agent as Row, command: 'generic-worker' }, transitions: [{ ...((definition.transitions as Row[])[0]), target: 'root', status: 'Reviewing' }, { ask: true, when: 'Operator approval' }], terminals: [{ name: 'logs', command: 'echo changed' }] });
    const yaml = readFileSync(join(project, '.torque', 'actions', `${name}.yaml`), 'utf8'); expect(yaml).toContain('worktree: false'); expect(yaml).toContain('deliverable:'); expect(yaml).toContain('KEEP:');
    const count = calls.filter((call) => call.cmd === 'save_action').length; await library.getByRole('button', { name: 'Duplicate', exact: true }).click(); await expect(library.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue(`${name}-copy`); expect(calls.filter((call) => call.cmd === 'save_action')).toHaveLength(count);
    hold = true; await library.getByRole('button', { name: 'Save action', exact: true }).click(); await expect.poll(() => Boolean(release)).toBe(true); await expect(library.getByRole('heading', { name: 'New action', exact: true })).toBeVisible(); await expect(library.getByRole('button', { name: 'New action', exact: true })).toBeDisabled(); refusal = 'list_actions'; hold = false; release!(); await expect(library.getByRole('heading', { name: `Edit ${name}-copy`, exact: true })).toBeVisible(); await expect(library.getByRole('alert')).toContainText('Catalog refresh failed'); const writes = calls.filter((call) => call.cmd === 'save_action').length; refusal = ''; await library.getByRole('button', { name: 'Retry catalog', exact: true }).click(); await expect(library.getByRole('alert')).toHaveCount(0); expect(calls.filter((call) => call.cmd === 'save_action')).toHaveLength(writes);
    await library.getByRole('textbox', { name: 'Name', exact: true }).fill('parity/renamed'); await library.getByRole('button', { name: 'Save action', exact: true }).click(); await expect(library.getByRole('heading', { name: 'Edit parity/renamed', exact: true })).toBeVisible();
    await library.getByRole('button', { name: 'Delete', exact: true }).click(); refusal = 'delete_action'; await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click(); await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Injected action refusal'); refusal = ''; await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(library.getByRole('button', { name: /parity\/renamed/ })).toHaveCount(0);
    await library.getByRole('button', { name: /parity\/build\s*project/ }).click(); await expect(prompt).toHaveValue(saved.prompt as string); await prompt.scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('actions-wide.png') });
    await page.setViewportSize({ width: 680, height: 850 }); await library.getByRole('button', { name: 'Preview', exact: true }).scrollIntoViewIfNeeded(); await expect(library.getByRole('button', { name: 'Preview', exact: true })).toBeInViewport(); await page.screenshot({ path: test.info().outputPath('actions-compact.png') });
    await page.getByRole('button', { name: 'Mission Control', exact: true }).click(); const hidden = calls.filter((call) => ['get_action', 'list_actions', 'render_action'].includes(String(call.cmd))).length; await reconnect(); expect(calls.filter((call) => ['get_action', 'list_actions', 'render_action'].includes(String(call.cmd)))).toHaveLength(hidden);
  } finally { rmSync(project, { recursive: true, force: true }); }
});
