import { expect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) { const result = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row }; expect(result.ok, result.error).toBe(true); return result.data; }
const args = (group: string, role: string) => ({ group, scope_kind: 'role', scope_group: group, scope_key: role, role_kind: role });
async function seed(request: APIRequestContext, group: string, role: string, text: string) {
  const current = await command(request, { cmd: 'behavior_overlay_read', ...args(group, role), seed: true });
  const proposal = await command(request, { cmd: 'behavior_overlay_propose', ...args(group, role), proposed_by_kind: 'user', proposed_by_agent_id: 'user', text, rationale: 'Isolated browser fixture', expected_base_version_id: (current.version as Row).id });
  await command(request, { cmd: 'behavior_overlay_user_approve', proposal_id: proposal.proposal_id });
}
test('Behavior editor owns group/role drafts, previews an empty change and submits its accepted base after refusal/reconnect', async ({ page, request }) => {
  test.setTimeout(70_000); const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const a = `Behavior A ${Date.now()}`; const b = `Behavior B ${Date.now()}`;
  for (const group of [a, b]) await command(request, { cmd: 'add_group', group });
  await seed(request, a, 'worker', 'Initial worker policy'); await seed(request, a, 'engineer', 'Initial engineer policy');
  await command(request, { cmd: 'ui_select_group', group: a }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'catalog' } });
  let socket: WebSocketRoute | undefined; let connections = 0; let held = false; let refuse = true; let release = () => {}; const writes: Row[] = []; let reads = 0;
  await page.routeWebSocket(/\/ws\?/, (route) => { route.connectToServer(); socket = route; connections++; });
  await page.route('**/api/cmd', async (route) => {
    const data = route.request().postDataJSON() as Row;
    if (['behavior_overlay_read', 'behavior_overlay_versions', 'behavior_overlay_proposals'].includes(String(data.cmd))) reads++;
    if (data.cmd === 'behavior_overlay_propose') { writes.push(data); if (refuse) { held = true; await new Promise<void>((resolve) => { release = resolve; }); await route.fulfill({ json: { ok: false, error: 'Injected behavior refusal' } }); return; } }
    await route.continue();
  });
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Dynamic Behavior', exact: true }); const kind = region.getByRole('combobox', { name: 'Behavior scope', exact: true }); const target = region.getByRole('combobox', { name: 'Behavior target', exact: true }); const text = region.getByRole('textbox', { name: 'Behavior instructions', exact: true }); const rationale = region.getByRole('textbox', { name: 'Proposal rationale', exact: true }); const propose = region.getByRole('button', { name: 'Propose change', exact: true });
    await kind.selectOption('role'); await target.selectOption('worker'); await expect(text).toHaveValue('Initial worker policy'); await text.fill(''); await rationale.fill('Clear obsolete worker policy'); await region.getByRole('button', { name: 'Preview draft diff', exact: true }).click(); await expect(region.getByLabel('Behavior draft diff')).toContainText('-Initial worker policy');
    await target.selectOption('engineer'); await expect(text).toHaveValue('Initial engineer policy'); await text.fill('Engineer draft'); await target.selectOption('worker'); await expect(text).toHaveValue(''); await expect(rationale).toHaveValue('Clear obsolete worker policy');
    await page.getByRole('button', { name: b, exact: true }).click(); await expect(page.getByText(`Workspace / ${b}`, { exact: true })).toBeVisible(); await kind.selectOption('role'); await target.selectOption('worker'); await expect(text).toBeVisible(); await text.fill('Other group draft'); await page.getByRole('button', { name: a, exact: true }).click(); await expect(page.getByText(`Workspace / ${a}`, { exact: true })).toBeVisible(); await expect(text).toHaveValue('');
    await text.fill('Local worker draft'); await text.evaluate((node: HTMLTextAreaElement) => { node.dataset.behaviorAnchor = 'same'; node.setSelectionRange(1, 6); }); const before = connections; await socket!.close({ code: 1012, reason: 'Behavior editor reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect(propose).toBeEnabled(); await expect(text).toBeFocused(); await expect(text).toHaveAttribute('data-behavior-anchor', 'same'); expect(await text.evaluate((node: HTMLTextAreaElement) => [node.selectionStart, node.selectionEnd])).toEqual([1, 6]);
    await text.fill(''); await propose.click(); await expect.poll(() => held).toBe(true); await expect(region.getByRole('button', { name: 'Submitting proposal…', exact: true })).toBeDisabled(); const previous = connections; await socket!.close({ code: 1012, reason: 'Pending behavior proposal' }); await expect.poll(() => connections).toBeGreaterThan(previous); expect(writes).toHaveLength(1); release(); await expect(region.getByRole('alert')).toContainText('Injected behavior refusal'); await expect(text).toHaveValue('');
    const base = String(((await command(request, { cmd: 'behavior_overlay_read', ...args(a, 'worker') })).version as Row).id); expect(writes[0]).toMatchObject({ ...args(a, 'worker'), text: '', rationale: 'Clear obsolete worker policy', expected_base_version_id: base });
    refuse = false; await expect(propose).toBeEnabled(); await propose.click(); await expect(region.getByText(/Proposal submitted:/)).toBeVisible(); expect(writes).toHaveLength(2); expect(writes[1]?.idempotency_key).toBe(writes[0]?.idempotency_key); await expect(propose).toBeDisabled();
    const rows = (await command(request, { cmd: 'behavior_overlay_proposals', ...args(a, 'worker') })).proposals as Row[]; const saved = rows.find((row) => row.rationale === 'Clear obsolete worker policy')!; expect(saved).toMatchObject({ base_version_id: base, proposed_text_bytes: 0 }); expect((await command(request, writes[1]!)).proposal_id).toBe(saved.id); const diff = await command(request, { cmd: 'behavior_overlay_diff', proposal_id: saved.id }); expect(String(diff.diff)).toContain('-Initial worker policy');
    await region.scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('behavior-editor.png') }); await page.setViewportSize({ width: 390, height: 844 }); expect(await region.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true); await page.screenshot({ path: test.info().outputPath('behavior-editor-narrow.png') }); await page.setViewportSize({ width: 1280, height: 720 });
    await page.getByRole('button', { name: 'Help', exact: true }).click(); const hiddenReads = reads; const old = connections; await socket!.close({ code: 1012, reason: 'Hidden behavior editor' }); await expect.poll(() => connections).toBeGreaterThan(old); await expect(page.getByLabel('Search documentation')).toBeVisible(); expect(reads).toBe(hiddenReads); await page.getByRole('button', { name: 'Catalog', exact: true }).click(); await expect(text).toHaveValue(''); await expect(rationale).toHaveValue('Clear obsolete worker policy'); await expect(propose).toBeDisabled();
  } finally { release(); }
});
test('Behavior editor loads a real Engineer scope and persists a user-authored proposal without applying it', async ({ page, request }) => {
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const group = `Behavior agent ${Date.now()}`; await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'update_group_settings', group, settings: { default_directory: '/private/tmp', git_worktree: false } }); await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'catalog' } });
  const id = String((await command(request, { cmd: 'add_engineer', name: group, group, provider: 'generic', command: '/bin/cat', directory: '/private/tmp' })).id);
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Dynamic Behavior', exact: true }); await region.getByRole('combobox', { name: 'Behavior target', exact: true }).selectOption(id);
    const input = region.getByRole('textbox', { name: 'Behavior instructions', exact: true }); await expect(input).toBeVisible(); const original = await input.inputValue(); await input.fill('Report focused verification evidence.'); await region.getByRole('textbox', { name: 'Proposal rationale', exact: true }).fill('Engineer scope parity fixture'); await region.getByRole('button', { name: 'Propose change', exact: true }).click(); await expect(region.getByText(/Proposal submitted:/)).toBeVisible();
    const proposals = (await command(request, { cmd: 'behavior_overlay_proposals', group, agent_id: id })).proposals as Row[]; expect(proposals.find((row) => row.rationale === 'Engineer scope parity fixture')).toMatchObject({ scope_kind: 'agent', scope_group: group, scope_key: id, proposed_by_kind: 'user', status: 'proposed', next_actor_kind: 'user' }); expect((await command(request, { cmd: 'behavior_overlay_read', group, agent_id: id })).text).toBe(original);
  } finally { await command(request, { cmd: 'remove_agent', id }); }
});
