import { expect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) { const result = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row }; expect(result.ok, result.error).toBe(true); return result.data; }
const args = (group: string, role: string) => ({ group, scope_kind: 'role', scope_group: group, scope_key: role, role_kind: role });
async function seed(request: APIRequestContext, group: string, role: string, text: string) {
  const current = await command(request, { cmd: 'behavior_overlay_read', ...args(group, role), seed: true });
  const proposal = await command(request, { cmd: 'behavior_overlay_propose', ...args(group, role), proposed_by_kind: 'user', proposed_by_agent_id: 'user', text, rationale: 'Isolated browser fixture', expected_base_version_id: (current.version as Row).id });
  await command(request, { cmd: 'behavior_overlay_user_approve', proposal_id: proposal.proposal_id });
}
test('Behavior editor owns group/role drafts, previews an empty change and submits its accepted base after refusal/reconnect', async ({ page, request }) => {
  test.setTimeout(70_000); const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const a = `Behavior A ${Date.now()}`; const b = `Behavior B ${Date.now()}`;
  for (const group of [a, b]) await command(request, { cmd: 'add_group', group });
  await seed(request, a, 'worker', 'Initial worker policy'); await seed(request, a, 'engineer', 'Initial engineer policy');
  await command(request, { cmd: 'ui_select_group', group: a }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'catalog' } });
  let socket: WebSocketRoute | undefined; let connections = 0; let held = false; let refuse = true; let release = () => {}; const writes: Row[] = []; let reads = 0;
  await page.routeWebSocket(/\/ws\?/, (route) => { route.connectToServer(); socket = route; connections++; });
  await page.route('**/api/cmd', async (route) => {
    const data = route.request().postDataJSON() as Row;
    if (['behavior_overlay_read', 'behavior_overlay_versions', 'behavior_overlay_proposals'].includes(String(data.cmd))) reads++;
    if (data.cmd === 'behavior_overlay_propose') { writes.push(data); if (refuse) { held = true; await new Promise<void>((resolve) => { release = resolve; }); await route.fulfill({ json: { ok: false, error: 'Injected behavior refusal' } }); return; } }
    await route.continue();
  });
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Dynamic Behavior', exact: true }); const kind = region.getByRole('combobox', { name: 'Behavior scope', exact: true }); const target = region.getByRole('combobox', { name: 'Behavior target', exact: true }); const text = region.getByRole('textbox', { name: 'Behavior instructions', exact: true }); const rationale = region.getByRole('textbox', { name: 'Proposal rationale', exact: true }); const propose = region.getByRole('button', { name: 'Propose change', exact: true });
    await kind.selectOption('role'); await target.selectOption('worker'); await expect(text).toHaveValue('Initial worker policy'); await text.fill(''); await rationale.fill('Clear obsolete worker policy'); await region.getByRole('button', { name: 'Preview draft diff', exact: true }).click(); await expect(region.getByLabel('Behavior draft diff')).toContainText('-Initial worker policy');
    await target.selectOption('engineer'); await expect(text).toHaveValue('Initial engineer policy'); await text.fill('Engineer draft'); await target.selectOption('worker'); await expect(text).toHaveValue(''); await expect(rationale).toHaveValue('Clear obsolete worker policy');
    await page.getByRole('button', { name: b, exact: true }).click(); await expect(page.getByText(`Workspace / ${b}`, { exact: true })).toBeVisible(); await kind.selectOption('role'); await target.selectOption('worker'); await expect(text).toBeVisible(); await text.fill('Other group draft'); await page.getByRole('button', { name: a, exact: true }).click(); await expect(page.getByText(`Workspace / ${a}`, { exact: true })).toBeVisible(); await expect(text).toHaveValue('');
    await text.fill('Local worker draft'); await text.evaluate((node: HTMLTextAreaElement) => { node.dataset.behaviorAnchor = 'same'; node.setSelectionRange(1, 6); }); const before = connections; await socket!.close({ code: 1012, reason: 'Behavior editor reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect(propose).toBeEnabled(); await expect(text).toBeFocused(); await expect(text).toHaveAttribute('data-behavior-anchor', 'same'); expect(await text.evaluate((node: HTMLTextAreaElement) => [node.selectionStart, node.selectionEnd])).toEqual([1, 6]);
    await text.fill(''); await propose.click(); await expect.poll(() => held).toBe(true); await expect(region.getByRole('button', { name: 'Submitting proposal…', exact: true })).toBeDisabled(); const previous = connections; await socket!.close({ code: 1012, reason: 'Pending behavior proposal' }); await expect.poll(() => connections).toBeGreaterThan(previous); expect(writes).toHaveLength(1); release(); await expect(region.getByRole('alert')).toContainText('Injected behavior refusal'); await expect(text).toHaveValue('');
    const base = String(((await command(request, { cmd: 'behavior_overlay_read', ...args(a, 'worker') })).version as Row).id); expect(writes[0]).toMatchObject({ ...args(a, 'worker'), text: '', rationale: 'Clear obsolete worker policy', expected_base_version_id: base });
    refuse = false; await expect(propose).toBeEnabled(); await propose.click(); await expect(region.getByText(/Proposal submitted:/)).toBeVisible(); expect(writes).toHaveLength(2); expect(writes[1]?.idempotency_key).toBe(writes[0]?.idempotency_key); await expect(propose).toBeDisabled();
    const rows = (await command(request, { cmd: 'behavior_overlay_proposals', ...args(a, 'worker') })).proposals as Row[]; const saved = rows.find((row) => row.rationale === 'Clear obsolete worker policy')!; expect(saved).toMatchObject({ base_version_id: base, proposed_text_bytes: 0 }); expect((await command(request, writes[1]!)).proposal_id).toBe(saved.id); const diff = await command(request, { cmd: 'behavior_overlay_diff', proposal_id: saved.id }); expect(String(diff.diff)).toContain('-Initial worker policy');
    await region.scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('behavior-editor.png') }); await page.setViewportSize({ width: 390, height: 844 }); expect(await region.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true); await page.screenshot({ path: test.info().outputPath('behavior-editor-narrow.png') }); await page.setViewportSize({ width: 1280, height: 720 });
    await page.getByRole('button', { name: 'Help', exact: true }).click(); const hiddenReads = reads; const old = connections; await socket!.close({ code: 1012, reason: 'Hidden behavior editor' }); await expect.poll(() => connections).toBeGreaterThan(old); await expect(page.getByLabel('Search documentation')).toBeVisible(); expect(reads).toBe(hiddenReads); await page.getByRole('button', { name: 'Catalog', exact: true }).click(); await expect(text).toHaveValue(''); await expect(rationale).toHaveValue('Clear obsolete worker policy'); await expect(propose).toBeDisabled();
  } finally { release(); }
});
test('Behavior editor loads a real Engineer scope and persists a user-authored proposal without applying it', async ({ page, request }) => {
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const group = `Behavior agent ${Date.now()}`; await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'update_group_settings', group, settings: { default_directory: '/private/tmp', git_worktree: false } }); await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'catalog' } });
  const id = String((await command(request, { cmd: 'add_engineer', name: group, group, provider: 'generic', command: '/bin/cat', directory: '/private/tmp' })).id);
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Dynamic Behavior', exact: true }); await region.getByRole('combobox', { name: 'Behavior target', exact: true }).selectOption(id);
    const input = region.getByRole('textbox', { name: 'Behavior instructions', exact: true }); await expect(input).toBeVisible(); const original = await input.inputValue(); await input.fill('Report focused verification evidence.'); await region.getByRole('textbox', { name: 'Proposal rationale', exact: true }).fill('Engineer scope parity fixture'); await region.getByRole('button', { name: 'Propose change', exact: true }).click(); await expect(region.getByText(/Proposal submitted:/)).toBeVisible();
    const proposals = (await command(request, { cmd: 'behavior_overlay_proposals', group, agent_id: id })).proposals as Row[]; expect(proposals.find((row) => row.rationale === 'Engineer scope parity fixture')).toMatchObject({ scope_kind: 'agent', scope_group: group, scope_key: id, proposed_by_kind: 'user', status: 'proposed', next_actor_kind: 'user' }); expect((await command(request, { cmd: 'behavior_overlay_read', group, agent_id: id })).text).toBe(original);
  } finally { await command(request, { cmd: 'remove_agent', id }); }
});

test('Behavior history shows provenance and requests a stale-safe rollback with separate approval', async ({ page, request }) => {
  test.setTimeout(90_000);
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const group = `Behavior history ${Date.now()}`; await command(request, { cmd: 'add_group', group }); await seed(request, group, 'worker', 'Historical trusted policy');
  const historical = (await command(request, { cmd: 'behavior_overlay_read', ...args(group, 'worker') })).version as Row;
  await seed(request, group, 'worker', 'Current replacement policy'); const initialBase = (await command(request, { cmd: 'behavior_overlay_read', ...args(group, 'worker') })).version as Row;
  await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'catalog' } });
  let socket: WebSocketRoute | undefined; let connections = 0; let holdComparison = true; let comparisonHeld = false; let releaseComparison = () => {}; let holdRollback = true; let rollbackHeld = false; let releaseRollback = () => {}; const writes: Row[] = [];
  await page.routeWebSocket(/\/ws\?/, (route) => { route.connectToServer(); socket = route; connections++; });
  await page.route('**/api/cmd', async (route) => {
    const data = route.request().postDataJSON() as Row;
    if (data.cmd === 'behavior_overlay_diff' && data.to_version_id && holdComparison) { holdComparison = false; comparisonHeld = true; await new Promise<void>((resolve) => { releaseComparison = resolve; }); }
    if (data.cmd === 'behavior_overlay_propose') { writes.push(data); if (holdRollback) { holdRollback = false; rollbackHeld = true; await new Promise<void>((resolve) => { releaseRollback = resolve; }); } }
    await route.continue().catch(() => {}); // A bounded browser read may have been aborted while deliberately held.
  });
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Dynamic Behavior', exact: true }); await region.getByRole('combobox', { name: 'Behavior scope', exact: true }).selectOption('role'); await region.getByRole('combobox', { name: 'Behavior target', exact: true }).selectOption('worker');
    const historicalRow = region.getByRole('article', { name: `Version ${String(historical.version_number)}`, exact: true }); await historicalRow.getByText('Version provenance', { exact: true }).click(); await expect(historicalRow.getByText(String(historical.text_sha256), { exact: true })).toBeVisible(); await expect(historicalRow.getByText('user · user', { exact: true })).toHaveCount(2); await expect(historicalRow.getByText(`${String(historical.text_bytes)} bytes`, { exact: true })).toBeVisible();
    await historicalRow.getByRole('button', { name: 'Review version and rollback', exact: true }).click(); let dialog = page.getByRole('dialog', { name: 'Review behavior version', exact: true }); const confirm = () => dialog.getByRole('button', { name: 'Confirm rollback request', exact: true }); const note = () => dialog.getByRole('textbox', { name: 'Rollback rationale', exact: true });
    await expect.poll(() => comparisonHeld).toBe(true); await expect(confirm()).toBeDisabled(); await note().fill('Restore the reviewed historical policy'); await expect(dialog.getByRole('alert')).toContainText('refresh timed out', { timeout: 20_000 }); await dialog.getByRole('button', { name: 'Reload version comparison', exact: true }).click(); await expect(confirm()).toBeEnabled(); releaseComparison(); await expect(dialog.getByLabel('Historical behavior diff')).toContainText('+Historical trusted policy'); expect(writes).toHaveLength(0);
    await dialog.getByText('Selected version provenance', { exact: true }).click(); await expect(dialog.getByText(String(historical.id), { exact: true })).toBeVisible(); await note().focus(); await note().evaluate((node: HTMLTextAreaElement) => { node.dataset.historyAnchor = 'same'; node.setSelectionRange(2, 9); }); const before = connections; await socket!.close({ code: 1012, reason: 'History comparison reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect(confirm()).toBeEnabled(); await expect(note()).toBeFocused(); await expect(note()).toHaveAttribute('data-history-anchor', 'same'); expect(await note().evaluate((node: HTMLTextAreaElement) => [node.selectionStart, node.selectionEnd])).toEqual([2, 9]);
    await confirm().click(); await expect.poll(() => rollbackHeld).toBe(true); expect(writes[0]).toMatchObject({ proposal_type: 'rollback', target_version_id: historical.id, expected_base_version_id: initialBase.id }); await expect(dialog.getByRole('button', { name: 'Requesting rollback…', exact: true })).toBeDisabled();
    await seed(request, group, 'worker', 'Newer concurrent policy'); const newestBase = (await command(request, { cmd: 'behavior_overlay_read', ...args(group, 'worker') })).version as Row; releaseRollback(); await expect(dialog.getByRole('alert')).toContainText('stale behavior overlay base version'); await expect(note()).toHaveValue('Restore the reviewed historical policy'); await expect(dialog.getByLabel('Historical behavior diff')).toContainText('-Newer concurrent policy'); await expect(confirm()).toBeEnabled();
    await confirm().scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('behavior-history-review.png') }); await page.setViewportSize({ width: 390, height: 844 }); expect(await dialog.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true); await confirm().scrollIntoViewIfNeeded(); await expect(confirm()).toBeInViewport(); await page.screenshot({ path: test.info().outputPath('behavior-history-review-narrow.png') }); await page.setViewportSize({ width: 1280, height: 720 });
    await confirm().click(); await expect(dialog.getByText(/Rollback proposal submitted:/)).toBeVisible(); expect(writes).toHaveLength(2); expect(writes[1]).toMatchObject({ expected_base_version_id: newestBase.id, target_version_id: historical.id, rationale: 'Restore the reviewed historical policy' }); expect(writes[1]?.idempotency_key).not.toBe(writes[0]?.idempotency_key);
    const proposals = (await command(request, { cmd: 'behavior_overlay_proposals', ...args(group, 'worker') })).proposals as Row[]; const saved = proposals.find((row) => row.proposal_type === 'rollback')!; expect(saved).toMatchObject({ status: 'proposed', next_actor_kind: 'user', approval_route: 'user', base_version_id: newestBase.id, target_version_id: historical.id }); expect((await command(request, writes[1]!)).proposal_id).toBe(saved.id); expect((await command(request, { cmd: 'behavior_overlay_read', ...args(group, 'worker') })).text).toBe('Newer concurrent policy');
    await dialog.getByRole('button', { name: 'Close version review', exact: true }).click(); await historicalRow.getByRole('button', { name: 'Review version and rollback', exact: true }).click(); dialog = page.getByRole('dialog', { name: 'Review behavior version', exact: true }); await expect(confirm()).toBeDisabled(); await expect(dialog.getByText(/Rollback proposal submitted:/)).toBeVisible(); await dialog.getByRole('button', { name: 'Close version review', exact: true }).click();
    await region.getByRole('button', { name: 'Review behavior diff', exact: true }).click(); const approval = page.getByRole('dialog', { name: 'Review behavior diff', exact: true }); await expect(approval.getByLabel('Behavior diff', { exact: true })).toContainText('+Historical trusted policy'); await approval.getByRole('button', { name: 'Approve behavior change', exact: true }).click(); await expect(approval.getByText('Behavior change approved.', { exact: true })).toBeVisible(); await approval.getByRole('button', { name: 'Close review', exact: true }).click();
    const applied = await command(request, { cmd: 'behavior_overlay_read', ...args(group, 'worker') }); expect(applied.text).toBe('Historical trusted policy'); expect(applied.version).toMatchObject({ id: historical.id, parent_version_id: historical.parent_version_id, source_proposal_id: historical.source_proposal_id }); const resolved = ((await command(request, { cmd: 'behavior_overlay_proposals', ...args(group, 'worker') })).proposals as Row[]).find((row) => row.id === saved.id); expect(resolved).toMatchObject({ status: 'applied', applied_version_id: historical.id, base_version_id: newestBase.id }); await page.reload(); await region.getByRole('combobox', { name: 'Behavior scope', exact: true }).selectOption('role'); await region.getByRole('combobox', { name: 'Behavior target', exact: true }).selectOption('worker'); await expect(region.getByRole('textbox', { name: 'Behavior instructions', exact: true })).toHaveValue('Historical trusted policy'); await expect(region.getByText(`Version ${String((applied.version as Row).version_number)} · Active`, { exact: true })).toBeVisible();
  } finally { releaseComparison(); releaseRollback(); }
});

test('Behavior approval persists every supported role and principal scope independently', async ({ page, request }) => {
  test.setTimeout(90_000);
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const group = `Behavior scopes ${Date.now()}`; await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'update_group_settings', group, settings: { default_directory: '/private/tmp', git_worktree: false } }); await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'catalog' } });
  const principals: { id: string; kind: string }[] = [];
  try {
    for (const kind of ['architect', 'engineer']) { const created = await command(request, { cmd: `add_${kind}`, group, name: `Behavior ${kind}`, provider: 'generic', command: '/bin/cat', directory: '/private/tmp', worktree: false }); principals.push({ id: String(created.id), kind }); }
    await page.goto('/'); const region = page.getByRole('region', { name: 'Dynamic Behavior', exact: true }); const targets = [...['architect', 'engineer', 'worker'].map((role) => ({ kind: 'role', target: role, label: role })), ...principals.map((agent) => ({ kind: 'agent', target: agent.id, label: agent.kind }))];
    for (const item of targets) {
      await region.getByRole('combobox', { name: 'Behavior scope', exact: true }).selectOption(item.kind); await region.getByRole('combobox', { name: 'Behavior target', exact: true }).selectOption(item.target); const input = region.getByRole('textbox', { name: 'Behavior instructions', exact: true }); await expect(input).toBeVisible(); await expect(region.getByRole('button', { name: 'Propose change', exact: true })).toBeEnabled();
      if (item.kind === 'role') await expect(region.getByText(/This additive .* role overlay/)).toContainText(item.target === 'worker' ? 'next worker dispatch' : 'next launch or relaunch'); else await expect(region.getByText(/only to the selected agent/)).toBeVisible();
      const instructions = `Keep verification scoped to ${item.kind} ${item.label}.`; const rationale = `${item.kind} ${item.label} acceptance`; await input.fill(instructions); await region.getByRole('textbox', { name: 'Proposal rationale', exact: true }).fill(rationale); await region.getByRole('button', { name: 'Propose change', exact: true }).click(); await expect(region.getByText(/Proposal submitted:/)).toBeVisible();
      const card = region.locator('article').filter({ hasText: rationale }); await expect(card.getByText('Set text', { exact: true })).toBeVisible(); await expect(card.getByText('user', { exact: true })).toBeVisible(); await card.getByRole('button', { name: 'Review behavior diff', exact: true }).click(); const modal = page.getByRole('dialog', { name: 'Review behavior diff', exact: true }); await expect(modal.getByLabel('Behavior diff', { exact: true })).toContainText(`+${instructions}`); await modal.getByRole('button', { name: 'Approve behavior change', exact: true }).click(); await expect(modal.getByText('Behavior change approved.', { exact: true })).toBeVisible(); await modal.getByRole('button', { name: 'Close review', exact: true }).click();
    }
    await page.reload();
    for (const item of targets) {
      const scope = { group, scope_kind: item.kind, scope_group: group, scope_key: item.target, ...(item.kind === 'agent' ? { agent_id: item.target } : { role_kind: item.target }) }; const persisted = await command(request, { cmd: 'behavior_overlay_read', ...scope }); expect(persisted.text).toBe(`Keep verification scoped to ${item.kind} ${item.label}.`); expect(persisted.version).toMatchObject({ scope_kind: item.kind, scope_group: group, scope_key: item.target, author_kind: 'user', approver_kind: 'user' });
      await region.getByRole('combobox', { name: 'Behavior scope', exact: true }).selectOption(item.kind); await region.getByRole('combobox', { name: 'Behavior target', exact: true }).selectOption(item.target); await expect(region.getByRole('textbox', { name: 'Behavior instructions', exact: true })).toHaveValue(persisted.text as string);
    }
  } finally { for (const agent of principals) await command(request, { cmd: 'remove_agent', id: agent.id }); }
});
