import { expect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) { const result = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row }; expect(result.ok, result.error).toBe(true); expect(result.data.type).not.toBe('error'); return result.data; }
test('quick verification applies only to completed pending tasks and reconciles live evidence without replaying it in draft saves', async ({ page, request }) => {
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const group = `Verification audit ${Date.now()}`; const ids: Record<string, string> = {}; const writes: Row[] = []; let socket: WebSocketRoute | undefined; let connections = 0;
  await page.route('**/api/cmd', async (route) => { const data = route.request().postDataJSON() as Row; if (data.cmd === 'board_update_task') writes.push(data); await route.continue(); });
  await page.routeWebSocket(/\/ws\?/, (client) => { socket = client; connections++; const server = client.connectToServer(); client.onMessage((raw) => { const frame = JSON.parse(String(raw)) as Row; if (frame.cmd === 'board_verify_task') writes.push(frame); server.send(raw); }); });
  const detail = async (name: string) => (await command(request, { cmd: 'task_detail', id: ids[name] })).task as Row;
  try {
    await command(request, { cmd: 'add_group', group });
    for (const [task, lane, verification_state] of [['Queued review', 'Backlog', 'pending'], ['Failed review', 'Done', 'failed'], ['Completed review', 'Done', 'pending'], ['Archived review', 'Done', 'attempted']]) ids[task!] = String((await command(request, { cmd: 'board_add_task', group, task, lane, verification_state, verification_notes: 'Saved note', verification_summary: { tests_run: 'Initial suite', manual_smoke_done: false, human_validation_pending: 'Check', deploy_needed: true } })).task_id);
    await command(request, { cmd: 'board_archive_tasks', ids: [ids['Archived review']] }); expect(await detail('Archived review')).toMatchObject({ lane: 'Archived', archived_from_lane: 'Done' });
    await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'board', controlTab: 'mission' } }); await page.goto('/');
    for (const task of ['Queued review', 'Failed review']) { await page.getByRole('button', { name: `Actions for ${task}`, exact: true }).click(); await expect(page.getByRole('menuitem', { name: 'Mark verified', exact: true })).toHaveCount(0); await page.keyboard.press('Escape'); }
    await page.getByText('Completed review', { exact: true }).dblclick(); const editor = page.getByRole('dialog', { name: 'Completed review', exact: true }); await editor.getByRole('tab', { name: 'Verification', exact: true }).click(); const note = editor.getByRole('textbox', { name: 'Verification notes', exact: true }); await note.fill('Retained review note'); await editor.getByRole('button', { name: 'Mark verified', exact: true }).first().click();
    await expect(editor.getByRole('combobox', { name: 'State', exact: true })).toHaveValue('passed'); await expect(editor.getByRole('checkbox', { name: 'Manual smoke done', exact: true })).toBeChecked(); await expect(editor.getByRole('button', { name: 'Mark verified', exact: true })).toHaveCount(0); await expect(note).toHaveValue('Retained review note');
    await note.focus(); await note.evaluate((node: HTMLTextAreaElement) => { node.dataset.owner = 'retained'; node.setSelectionRange(2, 8); }); const saved = await detail('Completed review'); await command(request, { cmd: 'board_update_task', id: ids['Completed review'], verification_summary: { ...(saved.verification_summary as Row), tests_run: 'Concurrent suite' } });
    await expect(editor.getByRole('textbox', { name: 'Tests run', exact: true })).toHaveValue('Concurrent suite'); await expect(note).toBeFocused(); expect(await note.evaluate((node: HTMLTextAreaElement) => [node.selectionStart, node.selectionEnd])).toEqual([2, 8]);
    const before = connections; await socket!.close({ code: 1012, reason: 'Verification draft reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect(note).toHaveAttribute('data-owner', 'retained'); await expect(note).toHaveValue('Retained review note'); await expect(editor.getByRole('combobox', { name: 'State', exact: true })).toHaveValue('passed');
    await page.screenshot({ path: test.info().outputPath('verification-live-draft.png'), animations: 'disabled' }); await editor.getByRole('button', { name: 'Save task', exact: true }).click(); await expect(editor).toHaveCount(0); expect(writes.find((row) => row.cmd === 'board_update_task')).toEqual({ cmd: 'board_update_task', id: ids['Completed review'], verification_notes: 'Retained review note', enforce_dispatch_edit_gate: true });
    expect(await detail('Completed review')).toMatchObject({ verification_state: 'passed', verification_notes: 'Retained review note', verification_summary: { tests_run: 'Concurrent suite', manual_smoke_done: true } });
    const verifiedSummary = (await detail('Completed review')).verification_summary as Row; expect(verifiedSummary).not.toHaveProperty('human_validation_pending'); expect(verifiedSummary).not.toHaveProperty('deploy_needed');
    await page.getByRole('button', { name: 'Archive', exact: true }).click(); await page.getByRole('button', { name: 'Actions for Archived review', exact: true }).click(); await page.getByRole('menuitem', { name: 'Mark verified', exact: true }).click(); await expect.poll(async () => (await detail('Archived review')).verification_state).toBe('passed');
    expect(writes.filter((row) => row.cmd === 'board_verify_task').map((row) => row.id)).toEqual([ids['Completed review'], ids['Archived review']]); await page.reload(); await page.getByRole('button', { name: 'Archive', exact: true }).click(); await page.getByRole('button', { name: 'Actions for Archived review', exact: true }).click(); await expect(page.getByRole('menuitem', { name: 'Mark verified', exact: true })).toHaveCount(0);
    await writeFile(test.info().outputPath('verification-commands.json'), JSON.stringify(writes, null, 2));
  } finally { for (const id of Object.values(ids)) await command(request, { cmd: 'board_remove_task', id }); await command(request, { cmd: 'remove_group', group }); }
});
