import { expect, test, type APIRequestContext } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) { const result = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row }; expect(result.ok, result.error).toBe(true); expect(result.data.type).not.toBe('error'); return result.data; }
test('card and details open external tickets in browser tabs; ID-only lookup recovers without losing task drafts', async ({ page, request, context }) => {
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const group = `Ticket opening ${Date.now()}`; const ids: string[] = []; const url = 'https://example.invalid/qa-ticket'; let reads = 0;
  // Browser navigation is real; no remote page or provider is contacted.
  await context.route('https://example.invalid/**', (route) => route.fulfill({ contentType: 'text/html', body: '<title>Local ticket fixture</title><h1>Ticket opened</h1>' }));
  await page.route('**/api/cmd', async (route) => { const data = route.request().postDataJSON() as Row; if (data.cmd === 'external_open_task') { reads++; if (reads === 2) { await route.fulfill({ json: { ok: true, data: { type: 'external_open', task_id: ids[1], url } } }); return; } } await route.continue(); });
  try {
    await command(request, { cmd: 'add_group', group });
    for (const [task, external_url] of [['Saved ticket', url], ['ID-only ticket', '']]) ids.push(String((await command(request, { cmd: 'board_add_task', group, task, lane: 'Backlog', provider: 'qa-local', external_id: 'LOCAL-1', external_url, board_sync: { enabled: false } })).task_id));
    await page.goto('/'); await page.getByRole('button', { name: /▦ Board/ }).click(); await page.getByRole('button', { name: group, exact: true }).click();
    const popup = async (click: () => Promise<unknown>) => { const opened = context.waitForEvent('page'); await click(); const ticket = await opened; await expect(ticket.getByRole('heading', { name: 'Ticket opened' })).toBeVisible(); expect(ticket.url()).toBe(url); expect(await ticket.evaluate(() => window.opener === null)).toBe(true); await ticket.close(); };
    await page.getByRole('button', { name: 'Actions for Saved ticket', exact: true }).click(); await popup(() => page.getByRole('menuitem', { name: 'Open external ticket', exact: true }).click());
    await page.getByText('Saved ticket', { exact: true }).dblclick(); const detail = page.getByRole('dialog', { name: 'Saved ticket', exact: true }); const draft = detail.getByRole('textbox', { name: 'Description', exact: true }); await draft.fill('Retained external draft'); await detail.getByRole('tab', { name: 'Integrations', exact: true }).click(); await popup(() => detail.getByRole('button', { name: 'Open ticket', exact: true }).click()); await expect(draft).toHaveValue('Retained external draft'); expect(reads).toBe(0); await detail.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.getByText('ID-only ticket', { exact: true }).dblclick(); const idDetail = page.getByRole('dialog', { name: 'ID-only ticket', exact: true }); await idDetail.getByRole('textbox', { name: 'Description', exact: true }).fill('Lookup retained draft'); await idDetail.getByRole('tab', { name: 'Integrations', exact: true }).click(); await idDetail.getByRole('button', { name: 'Open ticket', exact: true }).click();
    const lookup = page.getByRole('dialog', { name: 'Open external ticket', exact: true }); await expect(lookup.getByRole('alert')).toBeVisible(); await lookup.getByRole('button', { name: 'Retry ticket URL', exact: true }).click(); await expect(lookup.getByText(url, { exact: true })).toBeVisible(); await page.screenshot({ path: test.info().outputPath('resolved-ticket.png'), animations: 'disabled' });
    await popup(() => lookup.getByRole('button', { name: 'Open ticket', exact: true }).click()); await expect(lookup).toHaveCount(0); await expect(idDetail.getByRole('textbox', { name: 'Description', exact: true })).toHaveValue('Lookup retained draft'); expect(reads).toBe(2);
  } finally { for (const id of ids) await command(request, { cmd: 'board_remove_task', id }); await command(request, { cmd: 'remove_group', group }); }
});
