import { expect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) { const result = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row }; expect(result.ok, result.error).toBe(true); return result.data; }
async function isolated(request: APIRequestContext) { const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: Row } }).data.runtime; expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default'); }
async function prepare(request: APIRequestContext, group: string) { await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'ui_set_react_workspace_state', state: { version: 1, activePanel: 'control', controlTab: 'mission' } }); }
function summary(group: string, suffix = ''): Row { return { type: 'mission_control_summary', group, generated_at: '2026-09-25T19:00:00Z', sections: { needs_operator_now: { count: 25, truncated: true, items: [{ id: `${group}-gate`, title: `Gate ${group}${suffix}`, kind: 'approval', ref: { kind: 'task', id: 'fixture-task' }, severity: 'high', gate: 'verification', owner: { agent_name: 'Release Engineer' }, reason: 'Check the release evidence', recommended_next_action: 'review_evidence', timestamps: { updated_at: '2026-09-25T18:00:00Z' }, evidence_chips: ['checks green'], caveat_chips: ['external review pending'], deep_links: [{ surface: 'board', kind: 'task', task_id: 'fixture-task' }] }] }, at_risk_watchlist: { count: 0, items: [] }, in_flight: { count: 1, items: [{ id: `${group}-running`, title: `Build ${group}` }] }, recently_completed: { count: 0, items: [] } }, source_freshness: { tasks: { state: 'ok', count: 26 }, provider: { state: 'error', error: 'Fixture source is temporarily unavailable; retained evidence remains readable.' } } }; }
test('Mission Control owns group reads and retains disclosure, selection and search through refresh/reconnect', async ({ page, request }) => {
  test.setTimeout(75_000); await isolated(request); const a = `Mission A ${Date.now()}`; const b = `Mission B ${Date.now()}`; await prepare(request, b); await prepare(request, a);
  let connections = 0; let socket: WebSocketRoute | undefined; let held = false; let hold = true; let release = () => {}; let wrong = false; let suffix = ''; const reads: Row[] = [];
  await page.routeWebSocket(/\/ws\?/, (route) => { route.connectToServer(); socket = route; connections++; });
  await page.route('**/api/cmd', async (route) => { const data = route.request().postDataJSON() as Row; if (data.cmd !== 'get_mission_control') { await route.continue(); return; } reads.push(data); const group = String(data.group); const currentSuffix = suffix; if (group === a && hold) { held = true; await new Promise<void>((resolve) => { release = resolve; }); } await route.fulfill({ json: { ok: true, data: summary(wrong ? a : group, currentSuffix) } }); });
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Mission Control summary', exact: true }); await expect.poll(() => held).toBe(true); await expect(region.getByText('Loading Mission Control…', { exact: true })).toBeVisible(); await expect(region.getByText('No active risks in this group.', { exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: b, exact: true }).click(); await expect(region.getByRole('button', { name: `Inspect Gate ${b}`, exact: true })).toBeVisible(); hold = false; release(); await expect(region.getByRole('article', { name: `Gate ${a}`, exact: true })).toHaveCount(0);
    await region.getByRole('button', { name: `Inspect Gate ${b}`, exact: true }).click(); const toggle = region.getByRole('button', { name: 'Toggle In flight', exact: true }); await toggle.focus(); await page.keyboard.press('Enter'); await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    const search = region.getByRole('textbox', { name: 'Search Mission Control', exact: true }); await search.fill('Gate'); await search.evaluate((node: HTMLInputElement) => { node.dataset.missionAnchor = 'retained'; node.setSelectionRange(1, 3); });
    const before = connections; const priorReads = reads.length; suffix = ' revised'; await socket!.close({ code: 1012, reason: 'Mission summary reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect.poll(() => reads.length).toBeGreaterThan(priorReads); await expect(region.getByRole('button', { name: `Inspect Gate ${b} revised`, exact: true })).toHaveAttribute('aria-expanded', 'true'); await expect(search).toBeFocused(); await expect(search).toHaveAttribute('data-mission-anchor', 'retained'); expect(await search.evaluate((node: HTMLInputElement) => [node.selectionStart, node.selectionEnd])).toEqual([1, 3]); await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    wrong = true; await region.getByRole('button', { name: 'Refresh Mission Control summary', exact: true }).click(); await expect(region.getByRole('alert')).toContainText('wrong scope'); await expect(region.getByRole('article', { name: `Gate ${b} revised`, exact: true })).toBeVisible(); wrong = false; await region.getByRole('button', { name: 'Retry Mission Control', exact: true }).click(); await expect(region.getByRole('alert')).toHaveCount(0);
    await expect(region.getByText('26 cards', { exact: true })).toBeVisible(); await expect(region.getByText('Truncated', { exact: true })).toBeVisible(); const card = region.getByRole('article', { name: `Gate ${b} revised`, exact: true }); for (const value of ['Release Engineer', 'verification', 'review evidence', 'task:fixture-task', 'checks green', 'external review pending', 'board / task / fixture-task']) await expect(card).toContainText(value); await expect(region.getByRole('region', { name: 'Mission Control source freshness' })).toContainText('Fixture source is temporarily unavailable');
    await search.fill('no card matches'); await expect(region.getByRole('region', { name: 'Needs operator now', exact: true })).toContainText('No cards match'); await expect(region.getByText('26 cards', { exact: true })).toBeVisible(); await search.fill('Gate');
    await region.scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('mission-control.png') }); await page.setViewportSize({ width: 390, height: 844 }); await card.scrollIntoViewIfNeeded(); expect(await region.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true); await page.screenshot({ path: test.info().outputPath('mission-control-narrow.png') }); await page.setViewportSize({ width: 1280, height: 720 });
    await page.getByRole('button', { name: 'Help', exact: true }).click(); const hiddenReads = reads.length; const previous = connections; await socket!.close({ code: 1012, reason: 'Hidden Mission reconnect' }); await expect.poll(() => connections).toBeGreaterThan(previous); await expect(page.getByRole('textbox', { name: 'Search documentation' })).toBeVisible(); expect(reads).toHaveLength(hiddenReads);
    await page.getByRole('button', { name: 'Mission Control', exact: true }).click(); await expect(search).toHaveValue('Gate'); await expect(toggle).toHaveAttribute('aria-expanded', 'false'); await expect(region.getByRole('button', { name: `Inspect Gate ${b} revised`, exact: true })).toHaveAttribute('aria-expanded', 'true');
  } finally { release(); }
});
test('Mission Control dismisses real asks with refusal/retry, retained pending ownership and persisted/external updates', async ({ page, request }) => {
  test.setTimeout(60_000); await isolated(request); const group = `Mission dismissal ${Date.now()}`; await prepare(request, group);
  const first = String((await command(request, { cmd: 'board_add_task', group, task: 'Mission ask one', labels: ['torque:human'] })).task_id); const second = String((await command(request, { cmd: 'board_add_task', group, task: 'Mission ask two', labels: ['torque:human'] })).task_id);
  const firstId = `mc:task:${first}:ask`; const secondId = `mc:task:${second}:ask`; let socket: WebSocketRoute | undefined; let connections = 0; let release = () => {}; let held = false; let refuse = true; const dismissals: Row[] = [];
  await page.routeWebSocket(/\/ws\?/, (route) => { route.connectToServer(); socket = route; connections++; });
  await page.route('**/api/cmd', async (route) => { const data = route.request().postDataJSON() as Row; if (data.cmd === 'mission_control_dismiss') { dismissals.push(data); if (refuse) { held = true; await new Promise<void>((resolve) => { release = resolve; }); await route.fulfill({ json: { ok: false, error: 'Fixture dismissal refused' } }); return; } } await route.continue(); });
  try {
    await page.goto('/'); const region = page.getByRole('region', { name: 'Mission Control summary', exact: true }); const asks = region.getByRole('region', { name: 'Needs operator now', exact: true }); const card = asks.getByRole('article', { name: 'Mission ask one', exact: true }); const button = card.getByRole('button', { name: 'Dismiss Mission ask one', exact: true }); await expect(card).toBeVisible(); await card.getByRole('button', { name: 'Inspect Mission ask one', exact: true }).click(); await button.click(); await expect.poll(() => held).toBe(true); await expect(button).toBeDisabled();
    const before = connections; await socket!.close({ code: 1012, reason: 'Pending Mission dismissal' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect(button).toBeDisabled(); expect(dismissals).toHaveLength(1); release(); await expect(card.getByRole('alert')).toContainText('Fixture dismissal refused'); await expect(button).toBeEnabled();
    refuse = false; await button.click(); await expect(card).toHaveCount(0); await expect(region.getByRole('region', { name: 'At-risk watchlist', exact: true }).getByRole('article', { name: 'Mission ask one', exact: true })).toBeVisible(); expect(dismissals).toHaveLength(2); expect(dismissals[1]?.id).toBe(firstId); await expect(region.getByRole('button', { name: 'Toggle Needs operator now', exact: true })).toBeFocused(); await expect(region.getByRole('heading', { name: 'Read-only detail', exact: true })).toBeVisible();
    const summary = await command(request, { cmd: 'get_mission_control', group }); expect(JSON.stringify(summary.sections)).not.toContain(firstId); expect(JSON.stringify(summary.sections)).toContain(secondId);
    await page.reload(); await expect(asks.getByRole('article', { name: 'Mission ask two', exact: true })).toBeVisible(); await expect(card).toHaveCount(0); await command(request, { cmd: 'mission_control_dismiss', id: secondId }); await expect(asks.getByRole('article', { name: 'Mission ask two', exact: true })).toHaveCount(0); await expect(region.getByRole('region', { name: 'Needs operator now', exact: true })).toContainText('No operator gates are waiting right now.');
    expect(JSON.stringify((await command(request, { cmd: 'get_mission_control', group })).sections)).not.toContain(secondId);
  } finally { release(); }
});
