import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) {
  const response = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row };
  expect(response.ok, response.error).toBe(true); return response.data;
}
test('highlighted prompts retain native editing, geometry, reconnect drafts and unchanged save payloads', async ({ page, request }) => {
  const runtime = (await (await request.get('/api/runtime')).json() as { data: { runtime: { port: number; profile: string } } }).data.runtime;
  expect(runtime.port).not.toBe(18932); expect(runtime.profile).not.toBe('default');
  const project = mkdtempSync(join(tmpdir(), 'torque-prompt-parity-')); const group = `Prompt ${Date.now()}`; const name = 'parity/highlight';
  const original = '{{ TASK | default("all") }}';
  try {
    await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'update_group_settings', group, settings: { default_directory: project, git_worktree: false } }); await command(request, { cmd: 'ui_select_group', group }); await command(request, { cmd: 'save_action', name, scope: 'project', group, action: { prompt: original } });
    let socket: WebSocketRoute | undefined; let connections = 0; let refusal = false; const calls: Row[] = [];
    await page.routeWebSocket(/\/ws\?/, (connection) => { connection.connectToServer(); socket = connection; connections++; });
    await page.route('**/api/cmd', async (route) => { const data = route.request().postDataJSON() as Row; calls.push(data); if (refusal && data.cmd === 'save_action') await route.fulfill({ json: { ok: false, error: 'Injected prompt refusal' } }); else await route.continue(); });
    await page.goto('/'); await page.getByRole('button', { name: /◎ Control/ }).click(); await page.getByRole('button', { name: 'Actions', exact: true }).click(); const library = page.getByRole('region', { name: 'Actions library' }); await library.getByRole('button', { name: /parity\/highlight\s*project/ }).click();
    const prompt = library.getByRole('textbox', { name: 'Prompt', exact: true }); const backdrop = prompt.locator('..').locator('pre'); await expect(prompt).toHaveValue(original); await expect(backdrop).toHaveAttribute('aria-hidden', 'true'); await expect(backdrop.locator('[data-syntax="expression"]')).toHaveCount(1);
    const colors = await backdrop.evaluate((node) => Object.fromEntries(['expression', 'filter', 'string'].map((kind) => [kind, getComputedStyle(node.querySelector(`[data-syntax="${kind}"]`)!).color]))); expect(new Set(Object.values(colors)).size).toBe(3);
    const edited = '{% if TASK %}\n' + Array.from({ length: 24 }, (_, i) => `Line ${i}: {{ TASK | default("all") }} — Olá 👋 ${'long text '.repeat(9)}`).join('\n') + '\n{% endif %}\n{# note #}\n';
    await prompt.fill(edited); await prompt.press('End'); await page.keyboard.insertText('extra'); await prompt.press(process.platform === 'darwin' ? 'Meta+z' : 'Control+z'); await expect(prompt).toHaveValue(edited); expect(await backdrop.textContent()).toBe(`${edited}\u200b`);
    await prompt.evaluate((node) => node.scrollIntoView({ block: 'center' })); await expect(prompt).toBeInViewport({ ratio: 1 }); const before = await prompt.boundingBox(); expect(before).not.toBeNull(); await page.mouse.move(before!.x + before!.width - 4, before!.y + before!.height - 4); await page.mouse.down(); await page.mouse.move(before!.x + before!.width - 4, before!.y + before!.height + 56, { steps: 4 }); await page.mouse.up(); await expect.poll(async () => (await prompt.boundingBox())!.height).toBeGreaterThan(before!.height + 30); await expect(prompt).toBeInViewport({ ratio: 1 });
    await prompt.evaluate((node: HTMLTextAreaElement) => { node.focus(); node.setSelectionRange(2, 7); node.dataset.promptAnchor = 'original'; });
    // Native selection can queue caret scrolling for the next frame. Finish the
    // gesture before setting the operator's subsequent reading viewport.
    await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
    await prompt.evaluate((node) => { node.scrollTop = 140; }); const scroll = await prompt.evaluate((node) => node.scrollTop); await expect.poll(() => backdrop.evaluate((node) => node.scrollTop)).toBeCloseTo(scroll, 0);
    const dimensions = await prompt.evaluate((node) => { const mirror = node.previousElementSibling as HTMLElement; return { input: node.clientWidth, mirror: mirror.clientWidth, inputHeight: node.scrollHeight, mirrorHeight: mirror.scrollHeight, font: getComputedStyle(node).font, mirrorFont: getComputedStyle(mirror).font }; }); expect(dimensions.input).toBe(dimensions.mirror); expect(dimensions.inputHeight).toBeCloseTo(dimensions.mirrorHeight, 0); expect(dimensions.font).toBe(dimensions.mirrorFont);
    await test.info().attach('initial-geometry', { body: JSON.stringify({ ...dimensions, scroll, box: await prompt.boundingBox() }), contentType: 'application/json' }); const oldConnections = connections; const reads = calls.filter((call) => call.cmd === 'get_action').length; await socket!.close({ code: 1012, reason: 'Prompt reconnect' }); await expect.poll(() => connections).toBeGreaterThan(oldConnections); await expect.poll(() => calls.filter((call) => call.cmd === 'get_action').length).toBeGreaterThan(reads); await expect(prompt).toHaveValue(edited); await expect(prompt).toBeFocused(); await expect(prompt).toHaveAttribute('data-prompt-anchor', 'original'); expect(await prompt.evaluate((node: HTMLTextAreaElement) => [node.selectionStart, node.selectionEnd])).toEqual([2, 7]); await test.info().attach('reconnect-geometry', { body: JSON.stringify(await prompt.evaluate((node: HTMLTextAreaElement) => ({ scroll: node.scrollTop, mirror: (node.previousElementSibling as HTMLElement).scrollTop, height: node.clientHeight, scrollHeight: node.scrollHeight, width: node.clientWidth, font: getComputedStyle(node).font }))), contentType: 'application/json' }); expect(await prompt.evaluate((node) => node.scrollTop)).toBeCloseTo(scroll, 0); expect((await prompt.boundingBox())!.height).toBeGreaterThan(before!.height + 30);
    await page.screenshot({ path: test.info().outputPath('prompt-wide.png') }); await page.setViewportSize({ width: 680, height: 850 }); await prompt.scrollIntoViewIfNeeded(); await expect(prompt).toHaveValue(edited); const compact = await prompt.evaluate((node) => ({ input: node.clientWidth, mirror: (node.previousElementSibling as HTMLElement).clientWidth, scroll: node.scrollHeight, mirrorScroll: (node.previousElementSibling as HTMLElement).scrollHeight })); expect(compact.input).toBe(compact.mirror); expect(compact.scroll).toBeCloseTo(compact.mirrorScroll, 0); await page.screenshot({ path: test.info().outputPath('prompt-compact.png') });
    await page.emulateMedia({ forcedColors: 'active' }); await expect(backdrop).toBeHidden(); expect(await prompt.evaluate((node) => getComputedStyle(node).webkitTextFillColor)).not.toBe('rgba(0, 0, 0, 0)'); await expect(prompt).toHaveValue(edited); await page.emulateMedia({ forcedColors: 'none' });
    refusal = true; await library.getByRole('button', { name: 'Save action', exact: true }).click(); await expect(library.getByRole('alert')).toContainText('Injected prompt refusal'); await expect(prompt).toHaveValue(edited); refusal = false; await library.getByRole('button', { name: 'Save action', exact: true }).click(); await expect(library.getByText(`Saved project ${name}`, { exact: true })).toBeVisible(); expect((calls.filter((call) => call.cmd === 'save_action').at(-1)!.action as Row).prompt).toBe(edited); const persisted = edited; expect((await command(request, { cmd: 'get_action', group, name, scope: 'project' })).action).toMatchObject({ prompt: persisted }); await expect(prompt).toHaveValue(persisted);
    await library.getByRole('textbox', { name: 'Preview TASK', exact: true }).fill('Rendered task'); await library.getByRole('button', { name: 'Preview', exact: true }).click(); await expect(library.getByLabel('Rendered action prompt')).toContainText('Line 0: Rendered task'); await expect(prompt).toHaveValue(persisted);
  } finally { rmSync(project, { recursive: true, force: true }); }
});
