import { expect as baseExpect, test, type APIRequestContext, type WebSocketRoute } from '@playwright/test';
const expect = baseExpect.configure({ timeout: 15_000 });
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) { const body = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row }; expect(body.ok, body.error).toBe(true); return body.data; }
async function isolated(request: APIRequestContext) { const frame = await (await request.get('/api/runtime')).json() as { data: { runtime: { port: number; profile: string } } }; expect(frame.data.runtime.port).not.toBe(18932); expect(frame.data.runtime.profile).not.toBe('default'); }
test('AI runtime diagnostics follow partial deltas while preserving drafts, focus and owned start outcomes', async ({ page, request }) => {
  test.setTimeout(90_000); await isolated(request);
  const group = `AI runtime ${Date.now()}`; await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'ui_select_group', group });
  let ai: Row = { enabled: false, embeddings: { runtime: 'sentence_transformers', model_id: 'fixture-desired', active_model_id: 'fixture-active', active_dims: 1024, dependency: { status: 'missing', packages: ['sqlite-vec', 'sentence-transformers'], install_hint: 'make ai-deps' } }, index: { status: 'rebuild_pending', counts: { sources: 10, chunks: 30, indexed: 20, pending: 10, stale: 4, errors: 2 }, corpus: { tasks: true }, last_built_at: 1700000000, last_error: 'Fixture index failure', rebuild_warning: { required: true, reason: 'Fixture model changed' }, current_job: { id: 'old-job', status: 'error', mode: 'rebuild', message: 'Fixture previous job' } }, boot_summary: { enabled: true, status: 'stale', counts: { ready: 3, stale: 4, errors: 1 }, last_refreshed_at: 1700000000, last_error: 'Fixture summary failure' }, metering: { calls_24h: 5, input_tokens_24h: 120, output_tokens_24h: 40, cache_read_input_tokens_24h: 80, last_call_at: 1700000000 } };
  let ops: Row[] = []; let pulseCount = 0; let connections = 0; let socket: WebSocketRoute | undefined; const starts: Row[] = []; const releases: (() => void)[] = [];
  await page.routeWebSocket(/\/ws\?/, (route) => { connections += 1; socket = route; const server = route.connectToServer(); server.onMessage((message) => { const frame = JSON.parse(String(message)) as Row; if (frame.type === 'state') frame.ai_settings = ai; if (route === socket && frame.type === 'delta' && Array.isArray(frame.ops) && ops.length) { frame.ops = [...frame.ops as Row[], ...ops]; ops = []; } route.send(JSON.stringify(frame)); }); });
  const pulse = async (next: Row[]) => { ops = next; pulseCount += 1; await command(request, { cmd: 'update_group_settings', group, settings: { max_agents: pulseCount } }); };
  await page.route('**/api/cmd', async (route) => {
    const data = route.request().postDataJSON() as Row;
    if (data.cmd === 'get_ai_settings') { await route.fulfill({ json: { ok: true, data: { type: 'ai_settings', settings: ai } } }); return; }
    if (data.cmd === 'ai_index_start') { starts.push(data); const ordinal = starts.length; await new Promise<void>((resolve) => releases.push(resolve)); await route.fulfill({ json: ordinal === 1 ? { ok: false, error: 'Fixture index start refused' } : { ok: true, data: { type: 'ai_index_job', job: { id: 'fixture-new-job', status: 'queued', mode: 'incremental' }, settings: { ...ai, index: { status: 'building', counts: { indexed: 0 }, current_job: { id: 'fixture-new-job', status: 'queued' } } } } } }); return; }
    await route.continue();
  });
  await page.goto('/'); await page.getByRole('button', { name: /◎ Control/ }).click(); await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const dependencies = page.getByRole('region', { name: 'Embedding dependencies' }); const index = page.getByRole('region', { name: 'Vector index', exact: true }); const summary = page.getByRole('region', { name: 'Boot summaries and metering' });
  await expect(dependencies).toContainText('make ai-deps'); await expect(dependencies).toContainText('GB-scale'); await expect(index.getByRole('button', { name: 'Rebuild index', exact: true })).toBeDisabled();
  for (const value of ['Sources 10', 'Chunks 30', 'Indexed 20', 'Pending 10', 'Stale 4', 'Errors 2', 'fixture-active · 1024 dims', 'Fixture index failure', 'Fixture previous job']) await expect(index).toContainText(value);
  for (const value of ['Ready 3', 'Stale 4', 'Errors 1', 'Calls 5', 'Input 120', 'Output 40', 'Cache read 80', 'Fixture summary failure']) await expect(summary).toContainText(value);
  const directory = page.getByLabel('Default directory', { exact: true }); await directory.fill('/private/tmp/ai-runtime-draft'); const model = page.getByLabel('Embedding model', { exact: true }); await model.fill('unsaved-model'); await model.focus(); await model.evaluate((element: HTMLInputElement) => { element.setSelectionRange(2, 7); element.dataset.aiRuntimeAnchor = 'retained'; });
  await pulse([{ op: 'ai_index_status_update', index: { counts: { pending: 7 }, current_job: null }, embeddings: { active_model_id: 'new-active' } }, { op: 'ai_summary_status_update', boot_summary: { status: 'ready', counts: { errors: 0 } }, metering: { calls_24h: 9 } }]);
  await expect(index).toContainText('Pending 7'); await expect(index).toContainText('Chunks 30'); await expect(index).toContainText('new-active · 1024 dims'); await expect(summary).toContainText('Calls 9'); await expect(summary).toContainText('Input 120'); await expect(summary).not.toContainText('Fixture summary failure'); await expect(model).toBeFocused(); await expect(model).toHaveAttribute('data-ai-runtime-anchor', 'retained'); expect(await model.evaluate((element: HTMLInputElement) => [element.selectionStart, element.selectionEnd])).toEqual([2, 7]);
  ai = { ...ai, embeddings: { ...(ai.embeddings as Row), dependency: { status: 'available' } }, index: { status: 'building', counts: {}, current_job: { id: 'running-job', status: 'running' }, corpus: { tasks: true } } }; await pulse([{ op: 'ai_settings_update', schema_version: 1, settings: ai }]); await expect(index.getByRole('button', { name: 'Build index', exact: true })).toBeDisabled(); await expect(index).toContainText('running-job'); await expect(dependencies).not.toContainText('make ai-deps');
  ai = { ...ai, index: { status: 'not_built', counts: {}, current_job: null, corpus: { tasks: true } } }; await pulse([{ op: 'ai_index_status_update', index: ai.index }]); await expect(index.getByRole('button', { name: 'Build index', exact: true })).toBeEnabled();
  await index.getByRole('button', { name: 'Build index', exact: true }).click(); await expect.poll(() => starts.length).toBe(1); await expect(index.getByRole('button', { name: 'Starting index…', exact: true })).toBeDisabled(); const before = connections; await socket!.close({ code: 1012, reason: 'AI start pending reconnect' }); await expect.poll(() => connections).toBeGreaterThan(before); await expect(index.getByRole('button', { name: 'Starting index…', exact: true })).toBeDisabled(); expect(starts).toHaveLength(1); await expect(model).toHaveValue('unsaved-model'); releases[0]!(); await expect(index.getByRole('alert')).toContainText('Fixture index start refused');
  await index.getByRole('button', { name: 'Build index', exact: true }).click(); await expect.poll(() => starts.length).toBe(2);
  ai = { ...ai, index: { status: 'ready', counts: { indexed: 42 }, current_job: { id: 'fixture-new-job', status: 'complete', mode: 'incremental', message: 'Fixture all entries complete' }, corpus: { tasks: true } }, embeddings: { ...(ai.embeddings as Row), active_model_id: 'final-active' } };
  await pulse([{ op: 'ai_index_status_update', index: ai.index, embeddings: { active_model_id: 'final-active' } }]); await expect(index).toContainText('Indexed 42'); releases[1]!(); await expect(index.getByRole('status')).toContainText('Start request accepted'); await expect(index).toContainText('Fixture all entries complete'); await expect(index).toContainText('Indexed 42'); await expect(index.getByRole('button', { name: 'Rebuild index', exact: true })).toBeEnabled(); expect(starts).toEqual([{ cmd: 'ai_index_start', mode: 'incremental', confirm: true }, { cmd: 'ai_index_start', mode: 'incremental', confirm: true }]);
  await expect(directory).toHaveValue('/private/tmp/ai-runtime-draft'); await expect(model).toHaveValue('unsaved-model'); await dependencies.scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('ai-runtime.png') });
  await page.setViewportSize({ width: 390, height: 844 }); await index.scrollIntoViewIfNeeded(); for (const region of [dependencies, index, summary]) expect(await region.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true); await page.screenshot({ path: test.info().outputPath('ai-runtime-narrow.png') }); await summary.scrollIntoViewIfNeeded(); await page.screenshot({ path: test.info().outputPath('ai-summary-narrow.png') });
});
test('a real disabled-AI index start projects its completed job without loading models', async ({ page, request }) => {
  await isolated(request); await command(request, { cmd: 'update_ai_settings', settings: { ai_enabled: false } });
  const group = `Disabled AI index ${Date.now()}`; await command(request, { cmd: 'add_group', group }); await command(request, { cmd: 'ui_select_group', group }); let starts = 0;
  // Allow the UI action in environments without optional dependencies. The real
  // daemon remains disabled and exits the job before harvest/model inference.
  await page.route('**/api/cmd', async (route) => { const data = route.request().postDataJSON() as Row; if (data.cmd === 'get_ai_settings') { const response = await route.fetch(); const body = await response.json() as { data: { settings: Row } }; const embeddings = body.data.settings.embeddings as Row; embeddings.dependency = { status: 'available' }; await route.fulfill({ response, json: body }); return; } if (data.cmd === 'ai_index_start') starts += 1; await route.continue(); });
  await page.goto('/'); await page.getByRole('button', { name: /◎ Control/ }).click(); await page.getByRole('button', { name: 'Settings', exact: true }).click(); const index = page.getByRole('region', { name: 'Vector index', exact: true });
  await index.getByRole('button', { name: 'Build index', exact: true }).click(); await expect(index.getByRole('status')).toContainText('Start request accepted'); await expect(index.locator('[data-state="complete"]')).toBeVisible(); expect(starts).toBe(1);
  const settings = (await command(request, { cmd: 'get_ai_settings' })).settings as Row; expect(settings.enabled).toBe(false); expect((settings.index as Row).current_job).toBeNull(); await expect(index).toContainText('Indexed 0');
});
