import { expect, test, type APIRequestContext } from '@playwright/test';
type Row = Record<string, unknown>;
async function command(request: APIRequestContext, data: Row) {
  const result = await (await request.post('/api/cmd', { data })).json() as { ok: boolean; error?: string; data: Row };
  expect(result.ok, result.error).toBe(true); return result.data;
}
test('Thinking creates valid briefs, hydrates all fields, links notes and persists reviewed lifecycle', async ({ page, request }) => {
  const runtime = await (await request.get('/api/runtime')).json() as { data: { runtime: { port: number; profile: string } } };
  expect(runtime.data.runtime.port).not.toBe(18932); expect(runtime.data.runtime.profile).not.toBe('default');
  const group = `Thinking ${Date.now()}`;
  await command(request, { cmd: 'add_group', group });
  await page.goto('/'); await page.getByRole('button', { name: group, exact: true }).click();
  await page.getByRole('button', { name: /◇ Planning/ }).click(); await page.getByRole('button', { name: 'Thinking', exact: true }).click();
  await page.getByRole('button', { name: '＋ Note' }).click();
  await page.getByLabel('Title', { exact: true }).fill('Field evidence'); await page.getByLabel('Body', { exact: true }).fill('Observed operator problem');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: '＋ Brief' }).click();
  await page.getByLabel('Title', { exact: true }).fill('Reviewable brief');
  await expect(page.getByRole('button', { name: 'Create', exact: true })).toBeDisabled();
  await page.getByLabel('Problem or opportunity').fill('Operators need durable evidence');
  let fail = true;
  await page.route('**/api/cmd', async (route) => {
    const data = route.request().postDataJSON() as Row;
    if (data.cmd === 'idea_brief_create' && fail) { fail = false; await route.fulfill({ json: { ok: false, error: 'Injected creation failure' } }); }
    else await route.continue();
  });
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Injected creation failure');
  await expect(page.getByLabel('Problem or opportunity')).toHaveValue('Operators need durable evidence');
  await page.getByRole('button', { name: 'Create', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  const list = await command(request, { cmd: 'idea_brief_list', group });
  const id = (list.idea_briefs as Row[])[0]!.id;
  await page.getByRole('button', { name: /Reviewable brief/ }).click();
  await expect(page.getByLabel('Problem or opportunity')).toHaveValue('Operators need durable evidence');
  const values = { 'Why it matters': 'Reduce lost context', 'Proposed shape': 'A visible evidence trail', 'Smallest useful version': 'One linked note', 'Risks and tradeoffs': 'Keep the workflow small', 'Open questions': 'Who reviews the first draft?' };
  for (const [label, value] of Object.entries(values)) await page.getByLabel(label, { exact: true }).fill(value);
  await page.getByLabel('Scratchpad note', { exact: true }).selectOption({ label: 'Field evidence' });
  await page.getByLabel('Why this link matters').fill('Ground the proposal'); await page.getByRole('button', { name: 'Add link', exact: true }).click();
  await page.getByText('Read linked note', { exact: true }).click(); await expect(page.getByText('Observed operator problem', { exact: true }).last()).toBeVisible();
  await page.getByLabel('Refinement note', { exact: true }).fill('Initial evidence pass');
  await page.getByRole('button', { name: 'Record refinement' }).click();
  await expect(page.getByLabel('Refinement note', { exact: true })).toHaveValue('');
  await page.getByLabel('Why it matters', { exact: true }).fill('Latest unsaved review rationale');
  await page.getByLabel('Lifecycle note', { exact: true }).fill('Ready for product review');
  await page.getByRole('button', { name: 'Propose for review' }).click(); await expect(page.getByRole('status')).toContainText('Status: proposed');
  const detail = await command(request, { cmd: 'idea_brief_show', id });
  expect(detail).toMatchObject({ problem_opportunity: 'Operators need durable evidence', why_it_matters: 'Latest unsaved review rationale', proposed_shape: values['Proposed shape'], smallest_useful_version: values['Smallest useful version'], risks_tradeoffs: values['Risks and tradeoffs'], open_questions: values['Open questions'], status: 'proposed', thinking_links: [{ type: 'scratchpad_note', context: 'Ground the proposal' }], refinement_log: [{ note: 'Initial evidence pass' }], proposal: { proposal_only: true, created_task_id: '', dispatch_state: 'none' } });
  await page.getByRole('button', { name: 'Park', exact: true }).click(); await expect(page.getByRole('status')).toContainText('Status: parked');
  await page.getByRole('button', { name: 'Return to draft' }).click(); await expect(page.getByRole('status')).toContainText('Status: draft');
  await page.getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload(); await page.getByRole('button', { name: /◇ Planning/ }).click(); await page.getByRole('button', { name: 'Thinking', exact: true }).click();
  await page.getByRole('button', { name: /Reviewable brief/ }).click();
  await expect(page.getByLabel('Why it matters', { exact: true })).toHaveValue('Latest unsaved review rationale');
  await page.screenshot({ path: test.info().outputPath('thinking-brief.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Archive', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: /Reviewable brief/ })).toHaveCount(0);
  await page.getByLabel('Show archived Thinking').check(); await page.getByRole('button', { name: /Reviewable brief/ }).click();
  await expect(page.getByLabel('Problem or opportunity')).toHaveValue('Operators need durable evidence'); await expect(page.getByLabel('Problem or opportunity')).toBeDisabled();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: /Field evidence/ }).click();
  await page.getByLabel('Body', { exact: true }).fill('Updated field evidence'); await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await page.getByRole('button', { name: /Field evidence/ }).click();
  await expect(page.getByLabel('Body', { exact: true })).toHaveValue('Updated field evidence');
  await page.getByRole('button', { name: 'Archive', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: /Field evidence/ }).click(); await expect(page.getByLabel('Body', { exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Delete', exact: true }).click(); await page.getByRole('button', { name: 'Confirm delete', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('button', { name: /Field evidence/ })).toHaveCount(0);
});
